### ISSUE TITLE
please make it available for other systems

### ISSUE THREAD

**Issue by Zamino** [itamarcu/tokenmagic-automatic-wounds#1]
This is the module I am looking for since months. Unfortunately it doesn't work for Hexxen. Could you please make this module work for other systems?

**Comment by Deadlander** [comment]
I would love to see support for Savage Worlds Adventure Edition as well.  The attribute keys are:
data.wounds.max
data.wounds.value

Cheers!

**Comment by itamarcu** [comment]
Both of these are now included in v1.0.3 :)

@Deadlander - I assumed that the wounds in SWADE work in reverse, where an increase in wounds value implies taking wounds.  Let me know if that's wrong.

**Comment by Deadlander** [comment]
That is correct.

**Comment by Deadlander** [comment]
Just tested it and it works like a charm!
